export const GOLDEN_CASES = [
  {
    id: "scala_exact_200k_fleet",
    group: "exact_vin",
    name: "Scala I exact VIN stays ready for planning at 200k / 48m fleet",
    vin: "TMBER6NW2T3085406",
    plannedKm: 200000,
    contractMonths: 48,
    exploitationType: "fleet_standard",
    manualOverrides: {
      engine: "1.0 TSI 85 kW",
      gearbox: "Manual",
      drivetrain: "FWD",
    },
    pricing: {
      laborRate: 5500,
      oilPricePerLiter: 1800,
      tireCategory: "standard",
      laborDiscount: 0,
      partsDiscount: 0,
      oilDiscount: 0,
    },
    scenarioKmList: [120000, 150000, 200000],
    expected: {
      supported: true,
      status: "ready",
      internalStatus: "ready_exact",
      quoteReadiness: "ready",
      planReadiness: "ready",
      canPlan: true,
      minimumTotalCost: 500000,
      minimumEvents: 30,
      minimumConfirmedEvents: 20,
      minimumEstimatedEvents: 8,
      requiredEventTypes: ["oil_service", "brake_fluid", "spark_plugs"],
      forbiddenEventTypes: ["dsg_service", "haldex_service"],
    },
  },
  {
    id: "kodiaq_exact_200k_fleet",
    group: "exact_vin",
    name: "Kodiaq II exact / near exact path stays ready and scenario output matches main plan",
    vin: "TMBLN9PSXST067894",
    plannedKm: 200000,
    contractMonths: 48,
    exploitationType: "fleet_standard",
    manualOverrides: {
      gearbox: "DSG",
    },
    pricing: {
      laborRate: 5500,
      oilPricePerLiter: 1800,
      tireCategory: "standard",
      laborDiscount: 0,
      partsDiscount: 0,
      oilDiscount: 0,
    },
    scenarioKmList: [120000, 150000, 200000],
    expected: {
      supported: true,
      status: "ready",
      internalStatus: "ready_exact",
      quoteReadiness: "ready",
      planReadiness: "ready",
      canPlan: true,
      minimumTotalCost: 600000,
      minimumEvents: 35,
      minimumConfirmedEvents: 20,
      minimumEstimatedEvents: 10,
      requiredEventTypes: ["oil_service", "haldex_service"],
      forbiddenEventTypes: ["spark_plugs"],
    },
  },
  {
    id: "octavia_gap_manual_required",
    group: "exact_vin",
    name: "Octavia IV exact VIN now resolves cleanly and stays ready for planning",
    vin: "TMBAA8NX6TM006260",
    plannedKm: 200000,
    contractMonths: 48,
    exploitationType: "fleet_standard",
    manualOverrides: {
      engine: "",
      gearbox: "",
      drivetrain: "",
    },
    pricing: {
      laborRate: 5500,
      oilPricePerLiter: 1800,
      tireCategory: "standard",
      laborDiscount: 0,
      partsDiscount: 0,
      oilDiscount: 0,
    },
    expected: {
      supported: true,
      status: "ready",
      resolutionStatus: "fully_resolved",
      internalStatus: "ready_exact",
      quoteReadiness: "ready",
      planReadiness: "ready",
      canPlan: true,
      requiredEventTypes: ["oil_service", "spark_plugs"],
      forbiddenEventTypes: ["dsg_service", "haldex_service"],
    },
  },
  {
    id: "scala_manual_override_ready",
    group: "exact_vin",
    name: "Scala manual override path unlocks planning cleanly",
    vin: "TMBER6NW4T3081065",
    plannedKm: 200000,
    contractMonths: 48,
    exploitationType: "fleet_standard",
    manualOverrides: {
      engine: "1.0 TSI 85 kW",
      gearbox: "Manual",
      drivetrain: "FWD",
    },
    pricing: {
      laborRate: 5500,
      oilPricePerLiter: 1800,
      tireCategory: "standard",
      laborDiscount: 0,
      partsDiscount: 0,
      oilDiscount: 0,
    },
    expected: {
      supported: true,
      status: "ready",
      internalStatus: "ready_exact",
      quoteReadiness: "ready",
      planReadiness: "ready",
      canPlan: true,
      minimumTotalCost: 500000,
      minimumEvents: 30,
      requiredEventTypes: ["spark_plugs"],
      forbiddenEventTypes: ["dsg_service", "haldex_service"],
    },
  },
  {
    id: "fabia_basic_ready",
    group: "exact_vin",
    name: "Fabia IV baseline auto flow stays ready",
    vin: "TMBEE9PJ7R4067937",
    plannedKm: 120000,
    contractMonths: 36,
    exploitationType: "fleet_standard",
    manualOverrides: {
      engine: "",
      gearbox: "",
      drivetrain: "",
    },
    pricing: {
      laborRate: 5500,
      oilPricePerLiter: 1800,
      tireCategory: "standard",
      laborDiscount: 0,
      partsDiscount: 0,
      oilDiscount: 0,
    },
    expected: {
      supported: true,
      status: "ready",
      internalStatus: "ready_exact",
      quoteReadiness: "ready",
      planReadiness: "ready",
      canPlan: true,
      minimumTotalCost: 250000,
      minimumEvents: 18,
      requiredEventTypes: ["spark_plugs"],
      forbiddenEventTypes: ["dsg_service", "haldex_service"],
    },
  },
  {
    id: "invalid_vin_blocked",
    group: "failure_case",
    name: "Invalid VIN remains unsupported and blocked",
    vin: "INVALIDVIN1234567",
    plannedKm: 120000,
    contractMonths: 36,
    exploitationType: "fleet_standard",
    manualOverrides: {
      engine: "",
      gearbox: "",
      drivetrain: "",
    },
    pricing: {
      laborRate: 5500,
      oilPricePerLiter: 1800,
      tireCategory: "standard",
      laborDiscount: 0,
      partsDiscount: 0,
      oilDiscount: 0,
    },
    expected: {
      supported: false,
      status: "blocked",
      canPlan: false,
    },
  },
  {
    id: "kodiaq_exact_200k_rentacar",
    group: "exact_vin",
    name: "Kodiaq same VIN on rent-a-car stays on same core engine but gets higher cost pressure",
    vin: "TMBLN9PSXST067894",
    plannedKm: 200000,
    contractMonths: 48,
    exploitationType: "rentacar",
    manualOverrides: {
      gearbox: "DSG",
    },
    pricing: {
      laborRate: 5500,
      oilPricePerLiter: 1800,
      tireCategory: "standard",
      laborDiscount: 0,
      partsDiscount: 0,
      oilDiscount: 0,
    },
    scenarioKmList: [120000, 150000, 200000],
    expected: {
      supported: true,
      status: "ready",
      internalStatus: "ready_exact",
      quoteReadiness: "ready",
      planReadiness: "ready",
      canPlan: true,
      minimumCostPerKm: 3.5,
      minimumConfirmedEvents: 25,
      minimumEstimatedEvents: 12,
      requiredEventTypes: ["haldex_service"],
    },
  },
  {
    id: "octavia_dq200_no_dsg_service",
    group: "guardrail",
    name: "Octavia 1.5 TSI DQ200 must not create DSG oil service",
    mockDecoded: {
      supported: true,
      marka: "Skoda",
      model: "Octavia IV",
      fuelType: "Petrol",
      motorKod: "1.5 TSI 110 kW",
      gearboxCode: "DQ200",
      menjac: "DSG",
      drivetrain: "FWD",
      oilCapacity: 5,
      supportedSource: "mock",
      modelYear: 2024
    },
    plannedKm: 200000,
    contractMonths: 48,
    exploitationType: "fleet_standard",
    manualOverrides: {
      engine: "1.5 TSI 110 kW",
      gearbox: "DQ200 DSG",
      drivetrain: "FWD"
    },
    pricing: {
      laborRate: 5500,
      oilPricePerLiter: 1800,
      tireCategory: "standard",
      laborDiscount: 0,
      partsDiscount: 0,
      oilDiscount: 0
    },
    expected: {
      supported: true,
      status: "ready",
      canPlan: true,
      planReadiness: "ready",
      requiredEventTypes: ["spark_plugs"],
      forbiddenEventTypes: ["dsg_service", "haldex_service"]
    }
  },
  {
    id: "unknown_octavia_pattern_inferred_not_ready",
    group: "near_known_failure",
    name: "Unknown Octavia VIN keeps gearbox conflict partial and non-plannable",
    vin: "TMBAA8NX1TM999998",
    plannedKm: 120000,
    contractMonths: 36,
    exploitationType: "fleet_standard",
    manualOverrides: {
      engine: "",
      gearbox: "",
      drivetrain: "",
    },
    pricing: {
      laborRate: 5500,
      oilPricePerLiter: 1800,
      tireCategory: "standard",
      laborDiscount: 0,
      partsDiscount: 0,
      oilDiscount: 0,
    },
    expected: {
      supported: true,
      status: "provisional",
      resolutionStatus: "partial_inferred",
      internalStatus: "partial_inferred",
      quoteReadiness: "provisional",
      missingConfirmations: ["gearbox"],
      canPlan: true,
      engine: "DXDE",
      drivetrain: "FWD",
    },
  },
  {
    id: "superb_iv_fwd_dsg_no_haldex",
    group: "guardrail",
    name: "Superb IV FWD DSG exact VIN must create DSG service but never Haldex",
    vin: "TMBAH0NZ4SC056528",
    plannedKm: 120000,
    contractMonths: 36,
    exploitationType: "fleet_standard",
    manualOverrides: {},
    pricing: {
      laborRate: 5500,
      oilPricePerLiter: 1800,
      tireCategory: "standard",
      laborDiscount: 0,
      partsDiscount: 0,
      oilDiscount: 0,
    },
    expected: {
      supported: true,
      status: "ready",
      internalStatus: "ready_exact",
      quoteReadiness: "ready",
      planReadiness: "ready",
      canPlan: true,
      requiredEventTypes: ["dsg_service"],
      forbiddenEventTypes: ["haldex_service", "spark_plugs"],
      minimumConfirmedEvents: 10,
      minimumEstimatedEvents: 5,
    },
  },
  {
    id: "superb_ah0_2026_pattern_rule_closes_safely",
    group: "guardrail",
    name: "Superb AH0 2026 year-scoped DSG rule can close safely without creating Haldex",
    vin: "TMBAH0NZ0TC025102",
    plannedKm: 120000,
    contractMonths: 36,
    exploitationType: "fleet_standard",
    manualOverrides: {},
    pricing: {
      laborRate: 5500,
      oilPricePerLiter: 1800,
      tireCategory: "standard",
      laborDiscount: 0,
      partsDiscount: 0,
      oilDiscount: 0,
    },
    expected: {
      supported: true,
      status: "ready",
      internalStatus: "ready_exact",
      quoteReadiness: "ready",
      planReadiness: "ready",
      canPlan: true,
      requiredEventTypes: ["dsg_service"],
      forbiddenEventTypes: ["haldex_service", "spark_plugs"],
      minimumConfirmedEvents: 10,
      minimumEstimatedEvents: 5,
    },
  },
  {
    id: "kodiaq_ii_awd_dsg_has_haldex_and_dsg",
    group: "guardrail",
    name: "Kodiaq II AWD DSG exact VIN must create both DSG and Haldex services",
    vin: "TMBLN7PS9ST072766",
    plannedKm: 120000,
    contractMonths: 36,
    exploitationType: "fleet_standard",
    manualOverrides: {},
    pricing: {
      laborRate: 5500,
      oilPricePerLiter: 1800,
      tireCategory: "standard",
      laborDiscount: 0,
      partsDiscount: 0,
      oilDiscount: 0,
    },
    expected: {
      supported: true,
      status: "ready",
      internalStatus: "ready_exact",
      quoteReadiness: "ready",
      planReadiness: "ready",
      canPlan: true,
      requiredEventTypes: ["dsg_service", "haldex_service"],
      forbiddenEventTypes: ["spark_plugs"],
      minimumConfirmedEvents: 12,
      minimumEstimatedEvents: 5,
    },
  },

];

export const CROSS_CASE_ASSERTIONS = [
  {
    id: "rentacar_more_expensive_than_fleet_same_vin",
    leftCaseId: "kodiaq_exact_200k_rentacar",
    rightCaseId: "kodiaq_exact_200k_fleet",
    assertion: "costPerKmGreater",
    message:
      "Rent-a-car should have higher cost per km than the same VIN in fleet_standard mode.",
  },
  {
    id: "rentacar_not_fewer_events_than_fleet_same_vin",
    leftCaseId: "kodiaq_exact_200k_rentacar",
    rightCaseId: "kodiaq_exact_200k_fleet",
    assertion: "eventCountGreaterOrEqual",
    message:
      "Rent-a-car should not generate fewer events than the same VIN in fleet_standard mode.",
  },
];